import { mountLoader } from "./loader.js?v=202606081300";
import { initI18n } from "./i18n.js?v=202606081300";
import { setActiveNav, wireForms, mountAdviceNav, mountConseilsMobileHover, mountAppointmentPlanner, mountBudgetCalculator, mountM2Calculator, mountRentMaxCalculator, mountRateCalculator, mountWhatsAppFab, mountToTopFab, mountCardGalleries, mountFavorites, mountReveals, mountTeamBadgeSlide, mountContactValuesSlide, mountDossierChecklist, mountTopbarMenu, mountCountUps, mountTestimonials, mountTypewriters, mountDossierPrefill, mountConstructionToasts, mountPartnerComingSoonModal, mountSmartSearch, mountCantonBubbles, mountHomeSearchRanges, mountScrollIndicators, mountBnsRate } from "./ui.js?v=202606081300";
import { initRecherche } from "./recherche.js?v=202606081300";
import { initBiens } from "./biens.js?v=202606081300";
import { initHome } from "./home.js?v=202606081300";
import { initVideoFallbacks } from "./video-fallback.js?v=202606081300";
import { initListingPage } from "./listing-page.js?v=202606081300";
import { initVoiceSearch } from "./voice-search.js?v=202606081300";
import { initComingSoon } from "./coming-soon.js?v=202606081300";

const page = document.body.getAttribute("data-page");
if (page !== "coming-soon") {
  mountLoader();
  initI18n();
  initVoiceSearch();

  setActiveNav();
  mountTopbarMenu();
  mountConstructionToasts();
  mountPartnerComingSoonModal();
  mountAdviceNav();
  mountConseilsMobileHover();
  mountBnsRate();
  mountBudgetCalculator();
  mountM2Calculator();
  mountRentMaxCalculator();
  mountRateCalculator();
  wireForms();
  mountSmartSearch();
  mountHomeSearchRanges();
  mountCantonBubbles();
  mountAppointmentPlanner();
  mountTypewriters();
  mountDossierPrefill();
  mountDossierChecklist();
  initVideoFallbacks();
  mountWhatsAppFab();
  mountToTopFab();
  mountCardGalleries();
  mountFavorites();
  mountScrollIndicators();
  mountReveals();
  mountTeamBadgeSlide();
  mountContactValuesSlide();
  mountCountUps();
  mountTestimonials();
}
if (page === "home") initHome();
if (page === "recherche") initRecherche();
if (page === "biens") initBiens();
if (page === "listing") initListingPage();
if (page === "coming-soon") initComingSoon();
